# Generated by Django 5.1.1 on 2024-10-05 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('popularity', models.IntegerField(default=0)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='HorizontalBar',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('in_bundle', models.TextField(help_text='Список товаров в комплекте')),
                ('installation_type', models.CharField(max_length=255)),
                ('max_load', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=255)),
                ('dimensions', models.TextField(help_text='Габариты в см')),
                ('packaging_parameters', models.TextField(help_text='Параметры упаковки')),
                ('bar_diameter', models.CharField(max_length=100)),
                ('distance_between', models.CharField(max_length=100)),
                ('warranty', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('category', models.CharField(max_length=100)),
                ('calories', models.PositiveIntegerField()),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=5)),
                ('serving_size', models.CharField(max_length=50)),
                ('flavor', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='SwedishWall',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('in_bundle', models.TextField(help_text='Список товаров в комплекте')),
                ('installation_type', models.CharField(max_length=255)),
                ('max_load', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=255)),
                ('dimensions', models.TextField(help_text='Габариты в см')),
                ('packaging_parameters', models.TextField(help_text='Параметры упаковки')),
                ('bar_diameter', models.CharField(max_length=100)),
                ('distance_between', models.CharField(max_length=100)),
                ('warranty', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='WeightliftingProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('category', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('material', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('main.product',),
        ),
    ]
