# Generated by Django 5.1.1 on 2024-10-07 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_fitnessproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarbellRack',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('max_load', models.IntegerField(help_text='Максимальная нагрузка в кг')),
                ('height', models.DecimalField(decimal_places=2, help_text='Высота стойки в метрах', max_digits=5)),
                ('adjustable', models.BooleanField(default=False, help_text='Регулируемая высота')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('main.product',),
        ),
    ]
