# Generated by Django 5.1.1 on 2024-10-08 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_barbellrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='MartialArtsProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('equipment_type', models.CharField(choices=[('gloves', 'Перчатки'), ('helmet', 'Шлем'), ('uniform', 'Форма'), ('bag', 'Мешок для бокса'), ('protector', 'Защита')], help_text='Тип снаряжения', max_length=50)),
                ('material', models.CharField(blank=True, help_text='Материал снаряжения', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Товар для единоборств',
                'verbose_name_plural': 'Товары для единоборств',
            },
            bases=('main.product',),
        ),
    ]
