# Generated by Django 5.1.1 on 2024-10-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_martialartsproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='martialartsproduct',
            old_name='equipment_type',
            new_name='category',
        ),
    ]
